### ISSUE TITLE
code registers only 1 encoder step of 4.

### ISSUE THREAD

**Issue by Demonic098** [RalphBacon/226-Better-Rotary-Encoder---no-switch-bounce#1]
This code working correctly but it only registers only 1 encoder step of 4. In other words, 4 physical states are taken for 1 step.

**Comment by RalphBacon** [comment]
Correct. And that's the way I would expect it to work, as it is one complete "notch" or detent step on the rotary encoder. I don't see an advantage of knowing it is part-way through a step. If you think there is a case, let me know!

**Comment by Demonic098** [comment]
I guess you are right but i prefer to get all positions and if needed shift unneeded bits. And code can be optimised a lot.
