### ISSUE TITLE
needs two "clicks: per count

### ISSUE THREAD

**Issue by svdrummer** [RalphBacon/226-Better-Rotary-Encoder---no-switch-bounce#2]
Hello. I am using and Arduino D1 mini. (esp8266).
I have a generic RE and switching from a library based encoder to this one.
Most libraries let you select how many counts per revolution to set the count type.
I am wondering if anyone know how to have ...one click = one count. At the moment, two clicks = one count.
Cheers

**Comment by RalphBacon** [comment]
@svdrummer Hello!
Your "generic" rotary encoder might behave the same as my Bourns (PEC11R-4215F-S0012) model, where the manufacturer has decided it would give an extra indent (click) part way through the "full cycle". In some circumstances I'm sure this is desirable and useful, but not in our case.

The code I use here, ensures the full cycle has occurred before another detection takes place. So the intermediate detent (click) is merely half way through the cycle (one pin has changed value but we have not yet returned to the start position).

Thus the intermediate position within the cycle is not (yet) valid and should be ignored. This gives you the two-clicks = one count. 

The only way I've discovered to differentiate the two types is to look at the datasheet for "resolution" which is given in "pulses per revolution, or ppr" and "number of detents". If the two don't match then you will get extra clicks that are not what we expect (or want).

Other rotary encoders do it the way you expect, one click per full cycle. 

Of course, you could change the software to detect "half clicks" which is what the above gives you, which is basically a state change on either of the output pins (A, B or DT, CLK) without executing a "full" cycle back to the starting state.

**Comment by svdrummer** [comment]
Thank you for the feedback. I have cheap rotary encoders from AliExpress. 20 clicks per 360 degrees. I have noticed some SMD resistors on the PCB. I will remove them and try again.

**Comment by RalphBacon** [comment]
The SMD resistors are pull-up resistors so you don't have to worry about setting the input pins to INPUT_PULLUP in your code, that is all. But it does require a VCC connection for that to work.
